export const LIBRARY_ROUTE = '/'
export const ADMIN_ROUTE = '/admin'
export const REGISTER_ROUTE = '/register'
export const LOGIN_ROUTE = '/login'
export const BOOK_ROUTE = '/book'
// export const WISH_LIST_ROUTE = '/login'
